apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    component: mysql
    tier: control-plane
  name: mysql
  namespace: kube-system
spec:
  containers:
  - image: mysql:5.6
    imagePullPolicy: IfNotPresent
    name: mysql
    env:
      # Use secret in real usage
    - name: MYSQL_ROOT_PASSWORD
      value: password
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: data
  hostNetwork: true
  priorityClassName: system-node-critical
  securityContext:
    seLinuxOptions:
      type: spc_t
    seccompProfile:
      type: RuntimeDefault
  volumes:
  - hostPath:
      path: /var/lib/mysql
      type: DirectoryOrCreate
    name: data
status: {}
