apiVersion: v1
kind: Service
metadata:
  labels:
    app: ubuntu
  name: test-srv
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: http
  selector:
    app: ubuntu
  type: ClusterIP
