apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ubuntu
  name: ubuntu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ubuntu
    spec:
      hostNetwork: true
      containers:
      - image: ubuntu/nginx:1.18-20.04_beta
        name: ubuntu
        ports:
        - containerPort: 8088
          name: http
          protocol: TCP
        command: ["/bin/sleep", "3650d"]
        resources: {}
